<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="percheron">

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    
    <material name="yellow">
        <color rgba="1 1 0 1"/>
    </material>

    <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>

    <material name="olive">
        <color rgba="0.5 0.5 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

     <!-- Constants for robot dimensions -->
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="chassis_length" value="0.3"/>
    <xacro:property name="chassis_width" value="0.2"/>
    <xacro:property name="chassis_height" value="0.15"/>
    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.075"/>
    <xacro:property name="wheel_offset_y" value="0.1285"/>
    <xacro:property name="wheel_offset_z" value="0.015"/>
        
    <!-- base_link -->
    <link name="base_link">
    </link>

     <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- chassis -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis_link">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
    </link>

    <!--Macro Wheel-->
    <xacro:macro name="wheel_link" params="prefix place">
        <link name="${prefix}_wheel_${place}_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <!--Left Wheel Front-->
   <joint name="left_wheel_front_joint" type="fixed">
        <parent link="base_link" />
        <child link="left_wheel_front_link" />
        <origin xyz="0.15 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <xacro:wheel_link prefix="left" place="front" />


    <!--Left Wheel back-->
    <joint name="left_wheel_back_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_back_link" />
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <xacro:wheel_link prefix="left" place="back" />

    <!--Right Wheel Front-->
    <joint name="right_wheel_front_joint" type="fixed">
        <parent link="base_link" />
        <child link="right_wheel_front_link" />
        <origin xyz="0.15 ${-wheel_offset_y}  0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <xacro:wheel_link prefix="right" place="front" />

     <!--right Wheel Back-->
    <joint name="right_wheel_back_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_back_link" />
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <xacro:wheel_link prefix="right" place="back" />

</robot>